version: '2'
services:
  app:
    container_name: rails-app
    build: ./app/
    image: rails-app
    ports:
      - '80:80'
    volumes:
      - ~/git/github/dev_rails:/var/www/app/
    tty: true
    depends_on:
      - db
  db:
    container_name: rails-db
    build: ./mysql/
    image: rails-db
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
